# NumPy Tutorial

* NumPy is a python library.

* Numpy is used for working with arrays.

* Numpy is short for "Numerical Python".



1. Numpy library used for working with arrays.
2. It also works in the domain of linear algebra, fourier transform, and matrices.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

### Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

NumPy is written partially in python, but most of the parts that requires fast computation are written in C or C++ .

In [4]:
import numpy as np
# as -> alias
arr = np.array([1,2,3,4,5])

print(arr)
print(np.__version__)
print(type(arr))

[1 2 3 4 5]
1.24.3
<class 'numpy.ndarray'>


* To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray .

In [5]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


* Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays).

In [4]:
import numpy as np

arr0D = np.array(42)
arr1D = np.array([42,34,45,67])
arr2D = np.array([[42,45,56],[23,56,87]])
arr3D = np.array([[[42,36],[34,67]],[[23,84],[12,41]]])

print(arr0D)
print(arr1D)
print(arr2D)
print(arr3D)

42
[42 34 45 67]
[[42 45 56]
 [23 56 87]]
[[[42 36]
  [34 67]]

 [[23 84]
  [12 41]]]


* Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [3]:
import numpy as np

arr0D = np.array(42)
arr1D = np.array([42,34,45,67])
arr2D = np.array([[42,45,56],[23,56,87]])
arr3D = np.array([[[42,36],[34,67]],[[23,84],[12,41]]])

print(arr0D.ndim)
print(arr1D.ndim)
print(arr2D.ndim)
print(arr3D.ndim)

0
1
2
3


* Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

# In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

[[[[[1 2 3 4]]]]]
number of dimensions : 5


### Numpy Array Indexing

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

# using loop
for i in range (4):
  print(arr[i])

# we can implement mathematical operations on array

print(arr[0] + arr[1])

1
1
2
3
4
3


* Accessing 2-D Arrays

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


* Accessing 3-D Arrays

In [16]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[1, 1, 2])



6
12


* Negative Index

In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


### NumPy Array Slicing

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:])
print(arr[:4])
print(arr[1:5])
print(arr[1:5:2])
print(arr[-3:-1])
print(arr[::2])

[2 3 4 5 6 7]
[1 2 3 4]
[2 3 4 5]
[2 4]
[5 6]
[1 3 5 7]


* Slicing 2-D Arrays

In [29]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# From the second element, slice elements from index 1 to index 4 (not included):
print(arr[1, 1:4])

[7 8 9]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# From both elements, return index 2:
print(arr[0:2, 2])

[3 8]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


### NumPy Data Types

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

* The NumPy array object has a property called <b><i>dtype</i></b> that returns the data type of the array:

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [32]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


* Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:


In [49]:
import numpy as np

arr = np.array([1,2,3,4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


* For i, u, f, S and U we can define size as well.

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')
# Create an array with data type 4 bytes integer:
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


<b>ValueError:</b> In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [51]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

* Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [54]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')
newarr1 = arr.astype(int)


print(newarr)
print(newarr.dtype)
print(newarr1)
print(newarr1.dtype)

[1 2 3]
int32
[1 2 3]
int32


In [55]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### NumPy Array Copy vs View

### The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [58]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

x = arr.copy()
arr[0] = 42

print(arr)
print(x)
# print(type(arr))

[42  2  3  4  5  6]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [60]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

x = arr.view()
arr[0] = 42

print(arr)
print(x)

x[0] = 31
print(arr)
print(x)

[42  2  3  4  5  6]
[42  2  3  4  5  6]
[31  2  3  4  5  6]
[31  2  3  4  5  6]


* Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


### NumPy Array Shape



* Shape of an Array